// <auto-generated />
using System;
using E_learningProject.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace E_learningProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601120000_AddEmailMessagesAndAttachments")]
    partial class AddEmailMessagesAndAttachments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot is handled in ApplicationDbContextModelSnapshot.cs
        }
    }
}
